### ISSUE TITLE
Autocompile trying to compile any file, not only .less

### ISSUE THREAD

**Issue by lapega** [timdouglas/sublime-less2css#135]
When saving any file, even less2css config file, I have this error:
`lessc: ENOENT, open '/home/pgauna/.config/sublime-text-3/Packages/User/ui.less'`

Settings file:

```
{
  "autoCompile": true,
  "main_file": "ui.less"
}
```

* Sublime Text Build 3083
* Ubuntu 14.04 x64

**Comment by mattseymour** [comment]
The problem looks like it is caused because you are using the less2css users settings file.

Do you get the same problem if you are using a sublime project and setting the less2css settings within that?

Whilst a "fix" can be put in place I cannot be sure it will fix all instances of this issue. If you want to test this out.

Try modifying the `lesscompiler.py` file by adding in the following block around line 403 following the `for folder in proj_folders: ` block

```
if not proj_dir:
        try:
            proj_dir = proj_folders[0]
        except IndexError:
            print('[less2css] cannot determine project folder....')
```

**Comment by hooleez** [comment]
我也遇到了，前天还好好的，昨天开始公司2个同事出现这个情况，保存任何后缀的文件，都会触发编译，然后报错 lessc: ENOENT: no suck file or directory, open '...../style.less'

我的less2css用户配置文件如下
{
	"autoCompile": true,
	"createCssSourceMaps": true,
	"main_file": "style.less",
	"minName": true,
	"minify": false,
	"outputDir": "auto"
}

但奇怪的是，有的同事没事，就2个同事出现这个。

干净卸载Sublime Text 3之后，只安装less2css也不行。

实在想不出来是哪里出了问题。

**Comment by agfa555** [comment]
I'm having the exact same problem. It's compiling when saving any file not just LESS files.
Any update is appreciated.
Thanks!

**Comment by nivincp** [comment]
I am facing the exact the same issue too!

**Comment by gynekolog** [comment]
Same problem. Some progress?

**Comment by mattseymour** [comment]
This is now in master please update your plugins

**Comment by gynekolog** [comment]
Works, thank you!

**Comment by agfa555** [comment]
Perfect! Working! Thanks!
